### ISSUE TITLE
Add documentation about whether and how public contributions to this app are requested

### ISSUE THREAD

**Issue by bdsl** [nhsx/covid-19-app-android-ag-public#12]
The issue template as shown below suggests that the project maintainers want feedback through the NHS site rather than here:

In any case, since Github offers the public the chance to make issue reports and pull requests, it would be useful to have a note in the project readme file to say whether or not the project maintainers want these sort of contributions, or if Github is being used as a publishing platform only.

If contributions through github are wanted some guidance about how best to collaborate with others working on the project would useful - perhaps in a contributing.md file similar to https://gist.github.com/PurpleBooth/b24679402957c63ec426

> Thank you for your interest in this project
> We welcome feedback about the Test and Trace App, and this can be sent to us via the 
> https://faq.covid19.nhs.uk/create-case/ page on the website.

**Comment by ataraxia89** [comment]
Have any of the NHSX developers even answered any of these issues yet? It seems to be the external community just talking to each other and attempting to contribute.

High level issues should probably be reported on the NHS link you gave, but technical issues in code must be reported here and must be addressed by the developers.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome product suggestions on the above link - https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. This is not the primary working copy of the source code, and as such pull requests cannot be applied to this copy, else it will diverge from upstream.  When we fix issues, or change features upstream, the changes will become available in this repository at the next software release.
We will look into creating a CONTRIBUTING.md as you suggest. Thanks for that suggestion.

**Comment by bdsl** [comment]
@nhs-covid19 Thanks for the info. For this sort of case it would be very useful if Github implemented https://github.com/dear-github/dear-github/issues/84 .

**Comment by bdsl** [comment]
It's still not possible to disable pull requests permanently, but you can now disable them for six months: https://twitter.com/github/status/1311772722234560517

Do that a few times and the pandemic might be over and then this repository can be archived.
